### ISSUE TITLE
Encapsulate Reduce method

### ISSUE THREAD

**Issue by mhusainisurge** [Odonno/ReduxSimple#15]
Does the `Reduce` method need to be public? I suppose there's no harm, but there seems to be no real need to expose it by default.

**Comment by mhusainisurge** [comment]
Another thought: I am not sure why it need to even have a default implementation. Any reason it can't just be an `abstract` method? A store that never changes state is probably an extremely rare case.

**Comment by Odonno** [comment]
@mhusainisurge By default, it returns the same state. I copied the same behavior of redux in js but instead of using a `switch`, I used methods and the default one is relative to the `default` case in js.

And at least, devs don't have to do anything to have a proper Redux store working. It's a no-updated state implementation but that's the starting point.

**Comment by Odonno** [comment]
And on the other question, yes, the `Reduce` function should be `protected`.

**Comment by mhusainisurge** [comment]
Ok, just wanted to check about the default implementation. I'll make the method `protected`.
