### ISSUE TITLE
Project fails when using multiple feature states of the same type

### ISSUE THREAD

**Issue by IamPeek** [Odonno/ReduxSimple#72]
Hey Guys,

you got a cool framework there, but unfortunately it doesn´t work me on Xamarin-App. As soon as I add the Line "Store = new ReduxStore<RootState>(CreateReducers(), RootState.Initial, false);" to my App.cs, it crashes while creating the Sub-Reducers. Only information i get of exception: System.TypeInitializationException: 'The type initializer for 'MyApp' threw an exception.'

Can you help me ? :)

**Comment by IamPeek** [comment]
Okay I go the fail now, somehow he didnt like that I had 3 Sub-States with the same Type. Can someone explain to me how I can reuse a State-Type with the same (Sub-)Reducers for other Substates ?

**Comment by Odonno** [comment]
Hi @IamPeek 

I am not aware of the issue you're describing. Can you please provide a short reproduction code so that I can fix the issue?

Thank you.

**Comment by IamPeek** [comment]
![image](https://user-images.githubusercontent.com/11179810/79467243-dda12380-7ffd-11ea-869a-7ba3fa32c8e8.png)

**Comment by IamPeek** [comment]
Has something to do with the selectors i guess ? :)

**Comment by Odonno** [comment]
Good. I can reproduce your error. The error comes from here: https://github.com/Odonno/ReduxSimple/blob/cd8ad984e6897e455b8fd684543edbbe260cd694/ReduxSimple/Reducers.Sub.cs#L81

**Comment by IamPeek** [comment]
Soooo... you gonna fix it ? :D

**Comment by Odonno** [comment]
Well, I am trying to figure out a solution. The fact is that .NET reflection isn't helping me much on this. I assumed that each nested state would be of a different type. So that I match the type to know which reducers to apply to the given type.

I did it that way because I did not find a way to do the relation with the property path, ex: `RootState.NestedState1`. I will check.

**Comment by Odonno** [comment]
The fastest way for you to fix it would be to create 3 different types for each of your nested state.

**Comment by Odonno** [comment]
The other way around for me would be to apply the reducers to all nested state that match the type. But then this...

```cs
var reducers1 = CreateSubReducers(
  nestedReducers.ToArray(),
  SelectNested1 // THIS !
);
```

...would have no sense anymore.

I am not sure which way is the best way. I will keep looking at the reflection documentation but from now on, I did not find anything useful.

**Comment by Odonno** [comment]
@IamPeek Well, after a deep thinking, I come with a really smart solution to deal with this. I'll use the relentless use of references of C# as its advantage. Because with reference objects, I can test the equality of the updated feature state and all the properties of the parent state. 

So, it should work all the time.. and if it doesn't (not sure why) well, there will be no failure because we will fallback to the previous state anyway.

I'll ship a new version soon.

**Comment by Odonno** [comment]
v3.2.0 is now available. Let me know if your project now works like expected.

Thank you for your patience.

**Comment by IamPeek** [comment]
Hey Mate its working now. Thank your very much :)
Using this Framework for a bachelor thesis by the way :)

**Comment by Odonno** [comment]
Good. What is the subject of your bachelor thesis?
