### ISSUE TITLE
Can ReduxSimple be used in Xamarin Forms Applications?

### ISSUE THREAD

**Issue by rubiktubik** [Odonno/ReduxSimple#80]
I like this library and want to use it in a Xamarin Forms Application.
(In my case in a UWP-Application, which should later be extended to Android or iOS)

Is it possible to use it with forms and does someone already use it?

A difference what i already found is that in Xamarin Forms there is no `ObserveOnDispatcher()` Method

**Comment by Odonno** [comment]
Hi @rubiktubik 

Of course you can use it in a Xamarin Forms. ReduxSimple is a .NET Standard library so if your app can use a .NET standard, then you can use ReduxSimple. So yes Xamarin Forms apps can.

However, you cannot use the UWP packages because they are not compatible. We may prioritize to create the Xamarin Forms projects for ReduxSimple (for Entity and Router packages). But still, the main parts of ReduxSimple are ready to use, and reusable between all platforms.

I am not aware if anyone does use it in XForms. Sorry.

**Comment by Odonno** [comment]
BTW, `ObserveOnDispatcher` is a method yo ucan get rom ReactiveUI. I don't know if it's available for Xamarin Forms. I would have said yes but not sure.
