### ISSUE TITLE
Effects with async / Task support ?

### ISSUE THREAD

**Issue by RockNHawk** [Odonno/ReduxSimple#84]
Hi,

I needs do some API call / DB Operation   in `effects`, does this library supports `effects` with `Task` ?

**Comment by Odonno** [comment]
Hi @RockNHawk 

Of course. First, you need to know that this lib is using Rx.NET. So you will work a lot with the concept of `Observable`. So, in order to use effects, you need to provide `Observable`.

So, if you make API calls with `Task`, which is natural. You need first to convert these methods to `Observable`.

And if you want some code, here it is on the Sample project: https://github.com/Odonno/ReduxSimple/blob/master/ReduxSimple.Uwp.Samples/Pokedex/Effects.cs

Feel free to ask additional questions if you want. :)
